### ISSUE TITLE
What is DDFMv2?

### ISSUE THREAD

**Issue by Sangh0** [XuJiacong/PIDNet#18]
Hello, thank you for your research and papers.

I have two questions for you.
1. I wonder what is the DDFMv2 in models/model_utils.py. Can you explain details or related paper for it.
2. As I understand, it works like "Light Bag". if not can you explain or mentions related works?

Thank you.

**Comment by XuJiacong** [comment]
That is another module designed but was not used in this paper.

**Comment by Sangh0** [comment]
I will refer to the implementation.
thank you.
