### ISSUE TITLE
Code Sample on Testing on a Single image or video

### ISSUE THREAD

**Issue by ayoolaolafenwa** [XuJiacong/PIDNet#2]
Thank you so much @XuJiacong for your work in creating PIDNET. I want to test the pretrained model on images and videos but there is no straightforward code on doing that. Looking forward to your response.

**Comment by XuJiacong** [comment]
For you own dataset, you need to create a list for it (see the files in `data/list/cityscapes/`), then define the parameters by creating the .yaml files (see the files in `configs/cityscapes/`). Then you can just run the `tools/eval.py` to test the pretrained models.

**Comment by ayoolaolafenwa** [comment]
Thank you @XuJiacong!

**Comment by XuJiacong** [comment]
Do you have groudtruth for the image or video? Or you just want to get the prediction?

**Comment by ayoolaolafenwa** [comment]
> Do you have groudtruth for the image or video? Or you just want to get the prediction?

Yes! I want to get the prediction! Test it on a single image and obtain the masks results.

**Comment by XuJiacong** [comment]
Please see the Custom Inputs section for the solution. Thanks.

**Comment by ayoolaolafenwa** [comment]
> Please see the Custom Inputs section for the solution. Thanks.

Thank you so much @XuJiacong ! I was able to perform inference successfully on images.

**Comment by beiyu555** [comment]
> Thank you so much @XuJiacong for your work in creating PIDNET. I want to test the pretrained model on images and videos but there is no straightforward code on doing that. Looking forward to your response.

hello， Could you  share the code for the testing video，Thanks
