### ISSUE TITLE
Semantic loss and SB loss are always 0

### ISSUE THREAD

**Issue by whd007** [XuJiacong/PIDNet#29]
Hello.
Recently, I'll trying to train this model with my custom dataset.
Before that, I ran the example code first. Semantic Loss and SB Loss are always 0, is this normal?
Other Acc or BCE Loss are output normally.

**Comment by XuJiacong** [comment]
Hello,

That is not normal, the semantic loss and SB loss should be nonzero.

Thanks.

**Comment by whd007** [comment]
> 

I've traced the code, it always returns 0 where I get pixel_losses in criterion.py.
Do you have any ideas?

**Comment by wine-plum** [comment]
> Hello. Recently, I'll trying to train this model with my custom dataset. Before that, I ran the example code first. Semantic Loss and SB Loss are always 0, is this normal? Other Acc or BCE Loss are output normally.



> > > 
> > 
> > 
> > I've traced the code, it always returns 0 where I get pixel_losses in criterion.py. I checked that the input data is ok. (edge, image, and label) Do you have any ideas?
> 
> I found my problem. It was a class weight problem, and after correcting it, training is normal.

I have the same problem. Can you tell me how to solve it? Thanks.

**Comment by whd007** [comment]
> > Hello. Recently, I'll trying to train this model with my custom dataset. Before that, I ran the example code first. Semantic Loss and SB Loss are always 0, is this normal? Other Acc or BCE Loss are output normally.
> 
> > > > 
> > > 
> > > 
> > > I've traced the code, it always returns 0 where I get pixel_losses in criterion.py. I checked that the input data is ok. (edge, image, and label) Do you have any ideas?
> > 
> > 
> > I found my problem. It was a class weight problem, and after correcting it, training is normal.
> 
> I have the same problem. Can you tell me how to solve it? Thanks.

I had set the class weight to None. (In ./datasets/cityscapes.py - line 55)

**Comment by wangyue1015** [comment]
Hello, I don't quite understand the solution you said, could you please help me have a look, you can send it to 1210889663@qq.com, thank you

> I have observed that after passing through (In ./utils/function.py - line 36), the values of "model.module.sem_loss.criterion.weight" are all set to 0, which results in both Semantic loss and SB loss being 0. Then, the issue can be resolved by restoring the data in "model.module.sem_loss.criterion.weight" to the class_weights of Cityscapes dataset.

**Comment by AAAdecade** [comment]
> 你好，我不太明白你说的解决方案，你能帮我看一下吗，你可以发[给 1210889663@qq.com](mailto:1210889663@qq.com)，谢谢
> 
> > 我观察到，在通过（在 ./utils/function.py - 第 36 行）后，“model.module.sem_loss.criterion.weight”的值都设置为 0，这导致语义损失和 SB 损失都为 0。然后，可以通过将“model.module.sem_loss.criterion.weight”中的数据恢复到 Cityscapes 数据集的class_weights来解决该问题。

朋友您好！请问PIDNet在训练过程中，每隔5次epoch会出现一个0、10、20、30的东西进行更新参数，而5次epoch之内参数miou无变化，请问这是正常的吗？如下图：
![捕获](https://github.com/XuJiacong/PIDNet/assets/145337236/3036ef61-1100-4770-8ab2-607ccc7e66e3)
![1](https://github.com/XuJiacong/PIDNet/assets/145337236/57a04944-3c8b-49
![2](https://github.com/XuJiacong/PIDNet/assets/145337236/f21e3739-1555-4efd-a0ea-6fdc5abb9d33)
fb-b6c2-f2f007a0d582)
![3](https://github.com/XuJiacong/PIDNet/assets/145337236/8146ec1d-830d-43d9-8ed7-40ad6fb96f77)
