### ISSUE TITLE
Add ADB and BAG to BiSeNet(Res18)

### ISSUE THREAD

**Issue by KiveeDong** [XuJiacong/PIDNet#4]
Hi, PIDNet is really interesting! Thanks for your kindly sharing!
I'am using BiSeNet for other tasks. In the paper, I see ADB-Bag brings 1.3 mIoU improvement for BiSeNet, so I want to add this module to the BiSeNet, but I'am not sure the details I implement are correct.
Could you please kindly release the codes of BiSeNet equipped with ADB and Bag?

**Comment by XuJiacong** [comment]
Thanks for your remind and I will release it recently.

**Comment by KiveeDong** [comment]
> Thanks for your remind and I will release it recently.

@XuJiacong Thx! Waiting for your relasing!

**Comment by XuJiacong** [comment]
Please see the files in `models/others/`. Thanks.

**Comment by KiveeDong** [comment]
> Please see the files in `models/others/`. Thanks.

Thanks for your sharing again~
