### ISSUE TITLE
IndexError: index -1 is out of bounds for dimension 0 with size 0

### ISSUE THREAD

**Issue by 17648145240** [XuJiacong/PIDNet#42]
I encountered this problem while running train.py, which has been bothering me for a long time. Has anyone encountered this  problem?

![image](https://user-images.githubusercontent.com/107454783/226304235-a954481b-07c1-408c-bc59-1b7357408987.png)

tools/train.py
![image](https://user-images.githubusercontent.com/107454783/226305172-b3668a0e-37b9-4307-90f8-c54964b81281.png)

utils/function.py
![image](https://user-images.githubusercontent.com/107454783/226305526-1ab70b4b-9f2f-4c6b-8974-11c0fdb01cae.png)

**Comment by neverstoplearn** [comment]
have you solve it? i meet the same error.

**Comment by Unusual6** [comment]
I got the same error. I try to change BASE_SIZE( in XXX.yaml ) that can solve this problem.
![image](https://github.com/XuJiacong/PIDNet/assets/114602129/ac8aa527-1b53-41c3-90af-c6855a01c842)
