### ISSUE TITLE
training on single gpu

### ISSUE THREAD

**Issue by tanveer6715** [XuJiacong/PIDNet#5]
Thanks for your work and providing code. Is it possible to train it on single GPU using cityscapes dataset?

**Comment by XuJiacong** [comment]
It depends on the memory of your GPU. I used 2 A100 GPUs (40GB for each one) for training of cityscapes but I could train it on single RTX 3090 (24 GB) by reducing the batch size to 8. Thanks.

**Comment by XuJiacong** [comment]
Single gpu is much easier, you could just delete any code that throws error.  such as:
`````
    if torch.cuda.device_count() != len(gpus):
        print("The gpu numbers do not match!")
        return 0
`````
Usually you should check if `torch.cuda.device_count()` is equal to 1, but you can directly delete it.

**Comment by tanveer6715** [comment]
> Single gpu is much easier, you could just delete any code that throws error. such as:
> 
> ```
>     if torch.cuda.device_count() != len(gpus):
>         print("The gpu numbers do not match!")
>         return 0
> ```
> 
> Usually you should check if `torch.cuda.device_count()` is equal to 1, but you can directly delete it.

thank you it works. I am closing the issue. :)

**Comment by Rebufleming** [comment]
> It depends on the memory of your GPU. I used 2 A100 GPUs (40GB for each one) for training of cityscapes but I could train it on single RTX 3090 (24 GB) by reducing the batch size to 8. Thanks.

请问这种情况下（3090，Batch_size=8)，learning_rate需要改变吗？
