### ISSUE TITLE
Training on cityscapes dataset

### ISSUE THREAD

**Issue by xianxingChen** [XuJiacong/PIDNet#68]
您好！我使用camvid数据集训练时没有发生问题
但使用cityscapes数据集训练时，验证损失为0，训练1个epoch就中断了，显示“IndexError: index -1 is out of bounds for dimension 0 with size 0”。
![image](https://github.com/XuJiacong/PIDNet/assets/61687829/581d5139-1ad8-44db-a0b8-1134cba11475)
![image](https://github.com/XuJiacong/PIDNet/assets/61687829/8881c6b7-fe3b-462b-9e7e-9356acb3e0ff)
请问是什么原因呢

**Comment by jinleihu** [comment]
您好！我的问题跟您一样，请问您解决了吗？

**Comment by xianxingChen** [comment]
你可以debug一下，我debug后发现cityscapes.py里的class_weights都没加载上，所以损失函数一直是0
你可以看看是不是也是这个问题



在 2023-10-17 13:00:09，"jinleihu" ***@***.***> 写道：

您好！我的问题跟您一样，请问您解决了吗？

**Comment by jinleihu** [comment]
是这样的，改掉之后可以了，谢谢您

**Comment by Lv595** [comment]
> 您好！我使用camvid数据集训练时没有发生问题 但使用cityscapes数据集训练时，验证损失为0，训练1个epoch就中断了，显示“IndexError： index -1 is outout of bounds for dimension 0 with size 0”。 ![image](https://user-images.githubusercontent.com/61687829/274479607-581d5139-1ad8-44db-a0b8-1134cba11475.png) ![image](https://user-images.githubusercontent.com/61687829/274479842-8881c6b7-fe3b-462b-9e7e-9356acb3e0ff.png) 请问是什么原因呢

你好，请问你最后具体是怎么解决的的？

**Comment by jinleihu** [comment]
看上面那个老哥说的，我是直接把class_weights隐掉了

**Comment by jinleihu** [comment]
看上面那个老哥说的地方，我是直接把class_weights隐掉了

**Comment by Lv595** [comment]
> 看上面那个老哥说的地方，我是直接把class_weights隐掉了

感谢你的回复，问题我已经解决了。

**Comment by AAAdecade** [comment]
朋友您好，请问您复现PIDnet在cityscapes数据集实现了吗，能达到原文中的miou和处理速度吗？为什么官网给我反馈的test结果只有76.6😭

**Comment by AAAdecade** [comment]
> 看上面那个老哥说的地方，我是直接把class_weights隐掉了

朋友您好！请问PIDNet在训练过程中，每隔5次epoch会出现一个0、10、20、30的东西进行更新参数，而5次epoch之内参数miou无变化，请问这是正常的吗？如下图：
![捕获](https://github.com/XuJiacong/PIDNet/assets/145337236/a458c297-53c2-484f-ae06-bbfdfed0b4f7)
![1](https://github.com/XuJiacong/PIDNet/assets/145337236/cecaba9b-a8ea-45a0-b1fd-d7d9755dc27e)
![2](https://github.com/XuJiacong/PIDNet/assets/145337236/21a349a1-f298-4c1f-9bbb-a6ba30a9039b)
![3](https://github.com/XuJiacong/PIDNet/assets/145337236/bf71779d-8771-4d01-ade2-f5666cb5760b)
