### ISSUE TITLE
Using on a mobile device

### ISSUE THREAD

**Issue by rose-jinyang** [XuJiacong/PIDNet#7]
Hello
How are you?
Thanks for contributing to this project.
I want to customize PIDNet  network in order to use it on a mobile device.
I think that it is difficult to run even PIDNet-S model on a mobile device.
Is there any solution to reduce PIDNet network size?
Thanks

**Comment by XuJiacong** [comment]
Thanks. For mobile application, I would recommend to replace the traditional convolution by depthwise separable convolution or you can try PP-Liteseg, which is the state-of-art ultra-light model.

**Comment by rose-jinyang** [comment]
Thanks for your reply.

**Comment by Jumabek** [comment]
thank you @XuJiacong , 

Any idea about mobile speed, if I use for example Iphone 12?
