### ISSUE TITLE
Training on custom dataset

### ISSUE THREAD

**Issue by B4RT1M** [XuJiacong/PIDNet#81]
Hi, 

I wanted to try the PIDNet for a small custom Dataset of mine. I converted evrything as needed into the cityscape format and the loader seems to work. But when I try to start the training I got the following error message:
' RuntimeError: weight tensor should be defined either for all or no classes '

I am using the pidnet_small_cityscapes.yaml config file with an adjusted NUM_CLASSES parameter. 

Any kind of help would be appreciated.

**Comment by YasinBedirhanSimsek** [comment]
@B4RT1M Hi, could you please share how you solved it?

**Comment by B4RT1M** [comment]
Sure, 

I changed the label_mapping in line 43 of datasets/cityscapes.py regarding my own classes. 
Just this small change was needed. But it took me some time to see :) 
Hope I could help you.
