### ISSUE TITLE
How To Increase Model Output Size

### ISSUE THREAD

**Issue by YasinBedirhanSimsek** [XuJiacong/PIDNet#86]
I trained my model on 640x480 dataset with 3 classes, everything works ok

But I find that the size of the output is 80x60 which is a bit small. 

This causes interpolation to affect the result. 

Is it possible to increase the model output size?

**Comment by NimraJabeen** [comment]
Hello Yasin, 

Could you please provide the pacakges that we need for pidnet, I am trying using the one in hrnet but they have compatibility issues.

Best Regards,
Nimra

**Comment by qmm1234** [comment]
Hello, have you encountered a situation during training where the loss doesn't converge, and both semantic loss and sb loss remain consistently at zero? If not, could you provide details on how you set the parameters during training?
![微信图片_20240331103215](https://github.com/XuJiacong/PIDNet/assets/105531742/7575c2c5-6c70-4327-b27d-194534e07866)

**Comment by itri20607** [comment]
> e

you can use scale factor as 8 to get orignal size image as segmented mask

in pidnet.py file 
`self.final_layer = segmenthead(planes * 4, head_planes, num_classes, scale_factor=8)`

**Comment by itri20607** [comment]
> I trained my model on 640x480 dataset with 3 classes, everything works ok
> 
> But I find that the size of the output is 80x60 which is a bit small.
> 
> This causes interpolation to affect the result.
> 
> Is it possible to increase the model output size?

you can use scale factor as 8 to get orignal size image as segmented mask

in pidnet.py file
self.final_layer = segmenthead(planes * 4, head_planes, num_classes, scale_factor=8)

**Comment by YasinBedirhanSimsek** [comment]
> Hello, have you encountered a situation during training where the loss doesn't converge, and both semantic loss and sb loss remain consistently at zero? If not, could you provide details on how you set the parameters during training? ![微信图片_20240331103215](https://private-user-images.githubusercontent.com/105531742/318255964-7575c2c5-6c70-4327-b27d-194534e07866.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5ODY3MzgsIm5iZiI6MTcxMjk4NjQzOCwicGF0aCI6Ii8xMDU1MzE3NDIvMzE4MjU1OTY0LTc1NzVjMmM1LTZjNzAtNDMyNy1iMjdkLTE5NDUzNGUwNzg2Ni5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxM1QwNTMzNThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZTE0Y2U5YmY5ZGYyMzhiZTBjNjk0ZDRkNDQ4YjhmMTJjMWRlY2ViOGFmYjA5OGI1NWQ3MTVjNWUwYTdkNDZmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9kguBEuTf4FLadnPdQ3b8DvHgLQUxr9kkL5LNU4CtQ4)

No, I didn't have this problem. However, I had to modify lots of things about loss computation to fix training issues. I even asked chat-gpt to fix it.

**Comment by YasinBedirhanSimsek** [comment]
> > I trained my model on 640x480 dataset with 3 classes, everything works ok
> > But I find that the size of the output is 80x60 which is a bit small.
> > This causes interpolation to affect the result.
> > Is it possible to increase the model output size?
> 
> you can use scale factor as 8 to get orignal size image as segmented mask
> 
> in pidnet.py file self.final_layer = segmenthead(planes * 4, head_planes, num_classes, scale_factor=8)

Thank you, I will try that

**Comment by AAAdecade** [comment]
朋友您好！请问PIDNet在训练过程中，每隔5次epoch会出现一个0、10、20、30的东西进行更新参数，而5次epoch之内参数miou无变化，请问这是正常的吗？如下图：
![捕获](https://github.com/XuJiacong/PIDNet/assets/145337236/5ba3aa6c-3761-4f9d-93d6-6487d24c0902)
![1](https://github.com/XuJiacong/PIDNet/assets/145337236/11e15c65-54a1-4e01-ade0-c0f5a45112bf)
![2](https://github.com/XuJiacong/PIDNet/assets/145337236/f7d028c3-85b6-4b7d-abcd-abda45d3a240)
![3](https://github.com/XuJiacong/PIDNet/assets/145337236/a1a1de0a-70ee-4fcb-9fa7-7710efeaa809)
