### ISSUE TITLE
Why using d layer prediction to choose best model?

### ISSUE THREAD

**Issue by uyolo1314** [XuJiacong/PIDNet#9]
https://github.com/XuJiacong/PIDNet/blob/803851b7f825ce511f73ed55065e3061cbea0e4e/utils/function.py#L114-L128

**Comment by XuJiacong** [comment]
Can you specify your question?
I think you are asking why I generate the boundary loss in validate function? The answer is that I just want to know the total loss and only mIOU is used to choose best model.

**Comment by XuJiacong** [comment]
Please check the entire code step by step. the outputs for the model in validate function is generated by https://github.com/XuJiacong/PIDNet/blob/803851b7f825ce511f73ed55065e3061cbea0e4e/utils/utils.py#L21

Thanks for your kind remind. If you think there is no question, please close this issue.

**Comment by uyolo1314** [comment]
```
for i in range(nums):
  pos = confusion_matrix[..., i].sum(1)
  res = confusion_matrix[..., i].sum(0)
  tp = np.diag(confusion_matrix[..., i])
  IoU_array = (tp / np.maximum(1.0, pos + res - tp))
  mean_IoU = IoU_array.mean()
  logging.info('{} {} {}'.format(i, IoU_array, mean_IoU))
  if config.TEST.OUTPUT_INDEX == i:
      IoU_array_ = IoU_array
      mean_IoU_ = mean_IoU

  writer = writer_dict['writer']
  global_steps = writer_dict['valid_global_steps']
  writer.add_scalar('valid_loss', ave_loss.average(), global_steps)
  writer.add_scalar('valid_mIoU', mean_IoU_, global_steps)
  writer_dict['valid_global_steps'] = global_steps + 1
  return ave_loss.average(), mean_IoU_, IoU_array_
```
I think the final logged mIOU is logged in this way. Your code just uses the last as the final logged mIOU.

**Comment by XuJiacong** [comment]
You are correct, but the FullModel class just forwards the first two outputs, that is [x_extra_p, x_]. Please check it step by step.

**Comment by uyolo1314** [comment]
I got it.
