### ISSUE TITLE
dimention维度不匹配

### ISSUE THREAD

**Issue by wuchaotao** [XuJiacong/PIDNet#97]
我仔细看了一下代码，图片在训练前会经过rand_crop函数对图片进行裁剪，我设置的IMAGE_SIZE是[288,1400]，就会在训练前将图片裁剪为[288,1400]。所以我做了实验，数据集制作为[288,1400]时训练不会报维度错误，但是用[301,1400]尺寸是确实报了维度不匹配的问题，这个应该怎么解决呢。网络下采样操作要求训练时图片的尺寸是32的倍数，这个应该和数据集的图片尺寸没有关系吧

**Comment by wuchaotao** [comment]
使用[301,1400]尺寸训练图片时，都是在最后一个iter报错

**Comment by LemonWang0110** [comment]
@wuchaotao 兄弟你搞错了吧，哪来的下采样操作要求训练图尺寸是32的倍数？去看下pidnet.py，要求送入数据被8整除，所以你用301x1400肯定不行了。

**Comment by wuchaotao** [comment]
> @wuchaotao 兄弟你搞错了吧，哪来的下采样操作要求训练图尺寸是32的倍数？去看下pidnet.py，要求送入数据被8整除，所以你用301x1400肯定不行了。

感谢您的回复，明白问题的原因了

**Comment by AAAdecade** [comment]
朋友您好！请问PIDNet在训练过程中，每隔5次epoch会出现一个0、10、20、30的东西进行更新参数，而5次epoch之内参数miou无变化，请问这是正常的吗？如下图：
![捕获](https://github.com/XuJiacong/PIDNet/assets/145337236/3bade898-7d62-4edd-8b5b-5d80f48dce56)
![1](https://github.com/XuJiacong/PIDNet/assets/145337236/9b4057a3-49d8-48c8-9486-4b8d19e6858c)
![2](https://github.com/XuJiacong/PIDNet/assets/145337236/4ca4c94a-05c3-42ce-b3f1-5a6f3e5ba4f7)
![3](https://github.com/XuJiacong/PIDNet/assets/145337236/3b7bc868-ed99-4a6b-b5ed-c01ea0ee942c)
